name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 1.8
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # Install Chrome for Selenium tests
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
# Create reports directory
      - name: Create Reports Directory
        run: mkdir -p reports
      # Build and run tests with Maven
      - name: Build and Test with Maven
        run: mvn clean install -Denv="qa" -Dwebdriver.chrome.driver=/usr/bin/chromedriver
        env:
          CHROME_BIN: /usr/bin/google-chrome
          CHROME_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --remote-allow-origins=* --user-data-dir=/tmp/chrome-user-data-${{ github.run_id }}"

      # Debug: Check test-output directory
      - name: Debug Test Output
        if: always()
        run: |
          echo "Checking test-output directory:"
          ls -la test-output/ || echo "test-output directory not found"
# Archive reports folder
      - name: Archive Reports
        if: always()
        run: |
          if [ "$(ls -A reports)" ]; then
            echo "Archiving reports..."
            tar -czf reports.tar.gz reports/
            ls -la reports.tar.gz
          else
            echo "Reports directory is empty, creating empty archive"
            touch reports/empty.txt  # Ensure something exists to archive
            tar -czf reports.tar.gz reports/
          fi
     

    env:
      MAVEN_OPTS: '-Xmx1024m -XX:MaxPermSize=256m'
