name: CI Pipeline

# Trigger the workflow on push and pull requests to main branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 1.8
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'  # Eclipse Temurin JDK

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      # Build and run tests with Maven
      - name: Build and Test with Maven
        run: mvn clean install -Denv="qa"

      # Archive ExtentReports
      - name: Archive Test Reports
        if: always()  # Run even if tests fail
        run: |
          if [ -d "test-output" ]; then
            tar -czf test-output.tar.gz test-output/
          fi

      # Upload test artifacts
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-output.tar.gz
          retention-days: 7

    # Environment variables
    env:
      MAVEN_OPTS: '-Xmx1024m -XX:MaxPermSize=256m'  # Adjust for Java 8 and test execution
